name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b463acdeebda01635d5c29be2f477f321e9af33309b06f647947378aa9a9a3b6"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
