name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "101010.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d45e599cbd216cd2ba3c9f98726f12e46d23cce5d836d5708aabe21303ad420e"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
