name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "123.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbb2feffecbf956cda33226cfa383c3b5f963f90f78427820c3cf87e00bdd996"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
