name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c169a555aaac11cef07ccdcba811ce645a0bdd950cc76148347060eea51112dd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
