name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f60a169ac97fb1a904fdce83562a913b3084b7b595842dbe03181096686d79a8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
