name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f23c42d963bb503dd7d8eebe1d204cebb04e1d25a0e06f1f9e09afaac9580ca"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
