name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc6376396558864f75abdc538120d195d77a92f7667a3fb70ff329a859e87863"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
