name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9deaa16ddde46fb409718b1a31a15f35da59ef8ae8ca64cbcebe56976f4acb52"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
