name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3902b39cbd73bd7340c1e1542ccb85666c0e21dc4bb94e652ccb9e34a6a218"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
