name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5674b52ceedcf39016a50bf98f115a85480a8fad875691f8970032ee396c9eb1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
