name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "9.9.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08740dce9e0fc077700fb366c90c3672dff1511a04cc039a6a43ebe4b1924758"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
