name = "NTNH"
author = "Bufka2011"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fa49cad4b300af408ac0162d5af479079c6a650fb9b51ef656759e558a42012"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
